spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: account-service
                fallbackUri: forward:fallback/account

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: ticket-service
                fallbackUri: forward:/fallback/ticket

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"