server:
  port: 8501

spring:
  application:
    name: account-service
  data:
    cassandra:
      contact-points: 127.0.0.1
      keyspace-name: account
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      base-packages: com.mabay.accountservice
  boot:
    admin:
      client:
        url: http://localhost:8505

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"