server:
  port: 8501

spring:
  application:
    name: Account Service
  data:
    cassandra:
      contact-points: 127.0.0.1
      keyspace-name: account
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      base-packages: com.muratcanabay.cloudapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka