server:
  port: 8081

spring:
  data:
    cassandra:
      contact-points: 127.0.0.1
      keyspace-name: account
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      base-packages: com.muratcanabay.cloudapp