server:
  port: 8500

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8505

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"