version: '3.8'

services:
  cassandra:
    image: cassandra:4.0.1
    container_name: 'cassandraDB'
    ports:
      - '9042:9042'

  mysql:
    image: mysql:8.0.27
    container_name: 'MysqlDB'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: 'ElasticSearch'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'RabbitMQ'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'

  zipkin:
    image: openzipkin/zipkin:2.12.9
    container_name: 'ZipkinServer'
    ports:
      - '9411:9411'
